### DISCUSSION TITLE
Self signed certificate

### DISCUSSION THREAD

**Discussion by netsho** [FuzzyGrim/Yamtrack#440] [Q&A] [answered]
Hello,
Thank you for your time and this awesome self hosted application.

I'm requesting some help on this issue.

**Context**
I'm running yamtrack, nginx reverse proxy and authentik as podman containers. The three of them are using the same custom podman network. Yamtrack is behind nginx reverse proxy and using authentik as sso (only sso connections).
nginx reverse proxy is using self-signed certificate for https. Authentik is using another self-signed certificate to sign the requests. Both are from the same self-signed CA. All my services are LAN only.

**Problem**
When i first started the yamtrack container, i mounted the ca-certificates folder as a volume for the container. I added the environment variable `REQUESTS_CA_BUNDLE` to trust my own CA. It worked for authentication, i could access yamtrack through authentik. But when i tried to add a media, i had a server error:
```
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)')))
```
After some digging, i found another env variable that can be used with django `SSL_CERT_FILE`. Then, the authentication doesn't work anymore with authentik. Same error. Tried on multiple devices.
I could still visit yamtrack on my browser because the first authentication is still in cache. With this env, i could browse media from tmdb, MAL and others.

When i use both the env variables, i get the authentik problem (unable to get local issuer certificate).

Do you guys have any idea what should I do ?

Here is my podman-compose file for yamtrack container:
```
services:
  yamtrack:
    container_name: yamtrack
    image: ghcr.io/fuzzygrim/yamtrack:0.22.5
    restart: unless-stopped
    depends_on:
      yamtrack_db:
        condition: service_healthy
      yamtrack_redis:
        condition: service_healthy
    networks:
        - nginx-proxy-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - SECRET=${SECRET}
      - REDIS_URL=redis://yamtrack_redis:6379
      - DB_HOST=yamtrack_db
      - DB_NAME=${PG_DB}
      - DB_USER=${PG_USER}
      - DB_PASSWORD=${PG_PASS}
      - DB_PORT=5432
      - URLS=https://yamtrack.homelab-services.com
      - ALLOWED_HOSTS=yamtrack.homelab-services.com
      - ADMIN_ENABLED=true
      - REGISTRATION=true
      - WEB_CONCURRENCY=7
      - SOCIAL_PROVIDERS=allauth.socialaccount.providers.openid_connect
      - SOCIALACCOUNT_PROVIDERS={"openid_connect":{"OAUTH_PKCE_ENABLED":true,"APPS":[{"provider_id":"authentik","name":"Authentik","client_id":"***","secret":"***","settings":{"server_url":"https://authentik.homelab-services.com/application/o/yamtrack/.well-known/openid-configuration"}}]}}      
      - SOCIALACCOUNT_ONLY=true
      - REDIRECT_LOGIN_TO_SSO=true
      - VIRTUAL_HOST=yamtrack.homelab-services.com
      - CERT_NAME=homelab-services
      - SSL_CERT_FILE=/usr/local/share/ca-certificates/homelab-rootCA.crt
      #- REQUESTS_CA_BUNDLE=/usr/local/share/ca-certificates/homelab-rootCA.crt
    volumes:
      - /usr/local/share/ca-certificates/:/usr/local/share/ca-certificates/:ro
    env_file:
      - .env
```

Thanks
