### ISSUE TITLE
Internal Server Error: /login

### ISSUE THREAD

**Issue by mcanyucel** [FuzzyGrim/Yamtrack#146]
I get the following error log:

>yamtrack        | [2024-04-17 11:51:30 +0000] [22] [ERROR] Internal Server Error: /login
yamtrack        | Traceback (most recent call last):
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
yamtrack        |     response = get_response(request)
yamtrack        |                ^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
yamtrack        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
yamtrack        |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
yamtrack        |     return self.dispatch(request, *args, **kwargs)
yamtrack        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
yamtrack        |     return bound_method(*args, **kwargs)
yamtrack        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/debug.py", line 143, in sensitive_post_parameters_wrapper
yamtrack        |     return view(request, *args, **kwargs)
yamtrack        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
yamtrack        |     return bound_method(*args, **kwargs)
yamtrack        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
yamtrack        |     result = _process_exception(request, e)
yamtrack        |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
yamtrack        |     response = view_func(request, *args, **kwargs)
yamtrack        |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
yamtrack        |     return bound_method(*args, **kwargs)
yamtrack        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
yamtrack        |     response = view_func(request, *args, **kwargs)
yamtrack        |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/views.py", line 88, in dispatch
yamtrack        |     return super().dispatch(request, *args, **kwargs)
yamtrack        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
yamtrack        |     return handler(request, *args, **kwargs)
yamtrack        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/views/generic/edit.py", line 151, in post
yamtrack        |     return self.form_valid(form)
yamtrack        |            ^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/yamtrack/users/views.py", line 52, in form_valid
yamtrack        |     return super().form_valid(form)
yamtrack        |            ^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/views.py", line 107, in form_valid
yamtrack        |     auth_login(self.request, form.get_user())
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 126, in login
yamtrack        |     request.session.cycle_key()
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/contrib/sessions/backends/base.py", line 304, in cycle_key
yamtrack        |     self.create()
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/contrib/sessions/backends/cache.py", line 42, in create
yamtrack        |     self._session_key = self._get_new_session_key()
yamtrack        |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/contrib/sessions/backends/base.py", line 150, in _get_new_session_key
yamtrack        |     if not self.exists(session_key):
yamtrack        |            ^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/contrib/sessions/backends/cache.py", line 73, in exists
yamtrack        |     bool(session_key) and (self.cache_key_prefix + session_key) in self._cache
yamtrack        |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/core/cache/backends/base.py", line 300, in __contains__
yamtrack        |     return self.has_key(key)
yamtrack        |            ^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/core/cache/backends/redis.py", line 210, in has_key
yamtrack        |     return self._cache.has_key(key)
yamtrack        |            ^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/django/core/cache/backends/redis.py", line 130, in has_key
yamtrack        |     return bool(client.exists(key))
yamtrack        |                 ^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/redis/commands/core.py", line 1737, in exists
yamtrack        |     return self.execute_command("EXISTS", *names)
yamtrack        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 540, in execute_command
yamtrack        |     conn = self.connection or pool.get_connection(command_name, **options)
yamtrack        |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 1104, in get_connection
yamtrack        |     connection.connect()
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 288, in connect
yamtrack        |     self.on_connect()
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 391, in on_connect
yamtrack        |     self.read_response()
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 512, in read_response
yamtrack        |     response = self._parser.read_response(disable_decoding=disable_decoding)
yamtrack        |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yamtrack        |   File "/usr/local/lib/python3.11/site-packages/redis/_parsers/hiredis.py", line 133, in read_response
yamtrack        |     raise response
yamtrack        | redis.exceptions.AuthenticationError: Authentication required.

My docker-compose file is as follows:

```
version: "3"
services:
  yamtrack:
    container_name: yamtrack
    image: ghcr.io/fuzzygrim/yamtrack
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - SECRET=rcEm...uAz # 64 character
      - REDIS_URL=redis://redis:6379
    volumes:
      - /home/styx/containers/yamtrack/db:/yamtrack/db
    networks:
      - authelia_default
      - yamtrack_backend

  redis:
    container_name: yamtrack-redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - yamtrack_backend

volumes:
  redis_data:

networks:
  authelia_default:
    external: true
  yamtrack_backend:
```

Any ideas?

**Comment by FuzzyGrim** [comment]
I can't reproduce the error with and without Authelia.

```yml
version: "3"
services:
  yamtrack:
    container_name: yamtrack
    image: ghcr.io/fuzzygrim/yamtrack
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - SECRET=rcEmuAz
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./db:/yamtrack/db
    networks:
      - yamtrack_backend
    ports:
      - "8000:8000"

  redis:
    container_name: yamtrack-redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - yamtrack_backend

volumes:
  redis_data:
```

```yml
version: "3"
services:
  yamtrack:
    container_name: yamtrack
    image: ghcr.io/fuzzygrim/yamtrack
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - SECRET=rcEmuAz
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./db:/yamtrack/db
    networks:
      - proxy
      - yamtrack_backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yamtrack.entrypoints=https"
      - "traefik.http.routers.yamtrack.rule=Host(`yamtrack.domain.com`)"
      - "traefik.http.routers.yamtrack.tls=true"
      - "traefik.http.services.yamtrack.loadbalancer.server.port=8000"
      - "traefik.http.routers.yamtrack.middlewares=authelia@docker"

  redis:
    container_name: yamtrack-redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - yamtrack_backend

volumes:
  redis_data:

networks:
  proxy:
    external: true
  yamtrack_backend:
```

Did this happen on the first start up or was it all of a sudden? Could you try it without Authelia?

**Comment by mcanyucel** [comment]
> Did this happen on the first start up or was it all of a sudden? Could you try it without Authelia?

It happened on the first start. I will start without authelia but actually in the caddyfile (I use Caddy server) I do not secure the endpoint; I use Caddy in a container so I just add them to the same network to call them by container name. 
I will just retry again with some more tinkering around.

**Comment by mcanyucel** [comment]
BTW the funny thing is I can register a new account; I see the *Your account has been created, you can now log in!*  message with a green background in the sign up screen. The error pops up only when I try to log in.

Add: I can see the following lines in the log when registering:

> yamtrack        | [2024-04-17 15:00:49 +0000] [1] [INFO] Starting gunicorn 21.2.0
yamtrack        | [2024-04-17 15:00:49 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
yamtrack        | [2024-04-17 15:00:49 +0000] [1] [INFO] Using worker: sync
yamtrack        | [2024-04-17 15:00:49 +0000] [22] [INFO] Booting worker with pid: 22
yamtrack        | [2024-04-17 15:01:28 +0000] [22] [INFO] New user registered: mcanyucel at 78.162.191.152

**Comment by FuzzyGrim** [comment]
Then it's probably an issue with redis.

Could you check the following:
- `docker exec yamtrack printenv REDIS_URL` returns `redis://redis:6379`
- `docker exec yamtrack-redis redis-cli PING` returns `PONG`
- What does `docker logs yamtrack-redis` show when you try to log in?

**Comment by mcanyucel** [comment]
**Starting Note:** I think I have solved the issue, but I am adding my *failed attempts* below for future reference for anyone having similar issues. 

I inspected redis image via `docker inspect yamtrack-redis`, and checked the DNS names section. There are 3 names defined: *yamtrack-redis*, *redis*, and container id (See the end of the next section for the full response). Now we are using *redis* so it should work, because yamtrack is connected to two networks: *authelia_default* and *yamtrack_backend* (and no redis containers are connected to authelia). But it was not working as expected (see below for several experiments on the redis container); the redis connection is alive but there are no logs. In the end, I decided to set the first DNS name as the URL:

```
version: "3"
services:
  yamtrack:
    container_name: yamtrack
    image: ghcr.io/fuzzygrim/yamtrack
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - SECRET=<some secret>
      - REDIS_URL=redis://yamtrack-redis:6379
    volumes:
      - /home/styx/containers/yamtrack/db:/yamtrack/db
    networks:
      - authelia_default
      - yamtrack_backend

  redis:
    container_name: yamtrack-redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - yamtrack_backend

volumes:
  redis_data:


networks:
  authelia_default:
    external: true
  yamtrack_backend:
```

And voila, it works now!

## Failed attampts
As an additional info, if I try to log in with incorrect credentials, the stack can identify it so I see auth error in the logs:

```
[2024-04-18 07:00:02 +0000] [22] [ERROR] Failed login attempt for: mcanqweqwe at 78.162.191.152 # incorrect username and pass
[2024-04-18 07:02:20 +0000] [22] [ERROR] Failed login attempt for: mcanyucel at 78.162.191.152 # incorrect pass
```


> Then it's probably an issue with redis.
> 
> Could you check the following:
> 
>     * `docker exec yamtrack printenv REDIS_URL` returns `redis://redis:6379`
This indeed returns redis://redis:6379

>     * `docker exec yamtrack-redis redis-cli PING` returns `PONG`
This also returns `PONG`

>     * What does `docker logs yamtrack-redis` show when you try to log in?

This is the output of yamtrack-redis; 
```
1:C 18 Apr 2024 06:57:19.178 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:C 18 Apr 2024 06:57:19.178 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 18 Apr 2024 06:57:19.178 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 18 Apr 2024 06:57:19.178 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 18 Apr 2024 06:57:19.178 * monotonic clock: POSIX clock_gettime
1:M 18 Apr 2024 06:57:19.180 * Running mode=standalone, port=6379.
1:M 18 Apr 2024 06:57:19.183 * Server initialized
1:M 18 Apr 2024 06:57:19.183 * Loading RDB produced by version 7.2.4
1:M 18 Apr 2024 06:57:19.184 * RDB age 46 seconds
1:M 18 Apr 2024 06:57:19.184 * RDB memory usage when created 0.83 Mb
1:M 18 Apr 2024 06:57:19.184 * Done loading RDB, keys loaded: 0, keys expired: 0.
1:M 18 Apr 2024 06:57:19.184 * DB loaded from disk: 0.000 seconds
1:M 18 Apr 2024 06:57:19.184 * Ready to accept connections tcp
```
Weird enough, I do not see any entry about anything; this includes failed authentications, even new user registrations. I don't get it, how can the authentications correctly fail if there is no redis log? Then I don't know a line about redis, so it may be normal.

This is a weird weird issue, lol.

I was thinking, could it be connecting to the wrong redis instance, but then the REDIS_URL seems to be correct. The yamtrack is connected to two networks (authelia_default and backend), but there is no redis instance running on authelia_default. Below is the inspection result for redis:

```
styx@4o6q:~/containers/yamtrack$ sudo docker inspect yamtrack-redis
[
    {
        "Id": "81c76d772e76f6b1386c49db53f2895a9f37b9abee4a30add13293e6c17d15d2",
        "Created": "2024-04-18T07:14:31.171022095Z",
        "Path": "docker-entrypoint.sh",
        "Args": [
            "redis-server"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2024-04-18T07:14:31.589484017Z",
            "FinishedAt": "2024-04-18T07:14:55.138345193Z"
        },
        "Image": "sha256:435993df2c8d3a1508114cea2dd12ef4d6cbab5c7238bb8e587f20b18982c834",
        "ResolvConfPath": "/var/lib/docker/containers/81c76d772e76f6b1386c49db53f2895a9f37b9abee4a30add13293e6c17d15d2/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/81c76d772e76f6b1386c49db53f2895a9f37b9abee4a30add13293e6c17d15d2/hostname",
        "HostsPath": "/var/lib/docker/containers/81c76d772e76f6b1386c49db53f2895a9f37b9abee4a30add13293e6c17d15d2/hosts",
        "LogPath": "/var/lib/docker/containers/81c76d772e76f6b1386c49db53f2895a9f37b9abee4a30add13293e6c17d15d2/81c76d772e76f6b1386c49db53f2895a9f37b9abee4a30add13293e6c17d15d2-json.log",
        "Name": "/yamtrack-redis",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "yamtrack_yamtrack_backend",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "Mounts": [
                {
                    "Type": "volume",
                    "Source": "yamtrack_redis_data",
                    "Target": "/data",
                    "VolumeOptions": {}
                }
            ],
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware",
                "/sys/devices/virtual/powercap"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/fe2863142f7b91ed1314598e905b9b5b3e692965d264bdb02953d81797048bdd-init/diff:/var/lib/docker/overlay2/3a1a310501c23147d147c3b3503bc722c1e53cd17294b6baadbaf8763fc466d1/diff:/var/lib/docker/overlay2/989985de43523851996ec105ca12ce349a1d8c9cac03b4ed2d0ebae9a058c547/diff:/var/lib/docker/overlay2/44428ef97c7478e5e67b9a926761d94c56e9211d2e2da2a21e9e9e609620386e/diff:/var/lib/docker/overlay2/187f593fb81406dc9aae9a759810301d48db56c08bf061aa64ff0829fd30d17d/diff:/var/lib/docker/overlay2/c0b01f2326095f76f4e2214691ba49970b0651abc53a30cfc8ba0bda3534fb84/diff:/var/lib/docker/overlay2/6209cf7c0371513921c192fb4db725a0f073b0d1b3d3ecce0cdb945491066903/diff:/var/lib/docker/overlay2/204fdd2d3c8606b62435aa9a6cada7caeecb1a092832cadc97f1f72ddca2013c/diff:/var/lib/docker/overlay2/1881dafc056480e5d9cf539887419862d363fbdb01926654713392edef23b754/diff",
                "MergedDir": "/var/lib/docker/overlay2/fe2863142f7b91ed1314598e905b9b5b3e692965d264bdb02953d81797048bdd/merged",
                "UpperDir": "/var/lib/docker/overlay2/fe2863142f7b91ed1314598e905b9b5b3e692965d264bdb02953d81797048bdd/diff",
                "WorkDir": "/var/lib/docker/overlay2/fe2863142f7b91ed1314598e905b9b5b3e692965d264bdb02953d81797048bdd/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "yamtrack_redis_data",
                "Source": "/var/lib/docker/volumes/yamtrack_redis_data/_data",
                "Destination": "/data",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "81c76d772e76",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "6379/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.17",
                "REDIS_VERSION=7.2.4",
                "REDIS_DOWNLOAD_URL=http://download.redis.io/releases/redis-7.2.4.tar.gz",
                "REDIS_DOWNLOAD_SHA=8d104c26a154b29fd67d6568b4f375212212ad41e0c2caa3d66480e78dbd3b59"
            ],
            "Cmd": [
                "redis-server"
            ],
            "Image": "redis:7-alpine",
            "Volumes": {
                "/data": {}
            },
            "WorkingDir": "/data",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "cafd0dc25eacde2cd4d9b5021cc6274ebe8cab535103b64500d5c39c8e60ae11",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "",
                "com.docker.compose.image": "sha256:435993df2c8d3a1508114cea2dd12ef4d6cbab5c7238bb8e587f20b18982c834",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "yamtrack",
                "com.docker.compose.project.config_files": "/home/styx/containers/yamtrack/docker-compose.yaml",
                "com.docker.compose.project.working_dir": "/home/styx/containers/yamtrack",
                "com.docker.compose.service": "redis",
                "com.docker.compose.version": "2.26.1"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "a0796522cb8ae1ee50e2d4bdd223f3cc4eaba7c2ce2281432c891634f0b152f3",
            "SandboxKey": "/var/run/docker/netns/a0796522cb8a",
            "Ports": {},
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "yamtrack_yamtrack_backend": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "yamtrack-redis",
                        "redis"
                    ],
                    "MacAddress": "",
                    "NetworkID": "74db1df24162c49051ab2a24eb890894f5bc5f52fe9346608654d212650df8e5",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DriverOpts": null,
                    "DNSNames": [
                        "yamtrack-redis",
                        "redis",
                        "81c76d772e76"
                    ]
                }
            }
        }
    }
]
```
