### ISSUE TITLE
Unraid template/help

### ISSUE THREAD

**Issue by reitenth** [FuzzyGrim/Yamtrack#148]
Any chance in getting an unraid template? i am having some difficulties at the moment. thanks.

**Comment by reitenth** [comment]
this is what ive got so far 
![image](https://github.com/FuzzyGrim/Yamtrack/assets/94771708/4ee6a1aa-6783-4d25-8424-562972c23b91)

**Comment by FuzzyGrim** [comment]
Hey, I haven't used Unraid so I don't plan to learn how to create a template at the moment, but I can help with the setup.

PostreSQL is optional and for a simpler configuration I would recommend simply using SQLite. This is the `docker-compose.yml`:

```
version: "3"
services:
  yamtrack:
    container_name: yamtrack
    image: ghcr.io/fuzzygrim/yamtrack
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - SECRET=longstring
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./db:/yamtrack/db
    ports:
      - "8000:8000"

  redis:
    container_name: yamtrack-redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
```

So from the screenshot, the port the container internally uses is 8000, the path to the container internally is /yamtrack/db, and only two variables are needed, SECRET and REDIS_URL. I am not sure if Unraid allows you to configure two containers at once, if not, you would have to create a Redis container and then set the REDIS_URL in Yamtrack to `redis://IP:REDIS_PORT`,

**Comment by reitenth** [comment]
i tried that exact docker compose and these are the few logs i get 
![image](https://github.com/FuzzyGrim/Yamtrack/assets/94771708/df8ff342-1c9f-4eba-a19f-07bebeae2116)
![image](https://github.com/FuzzyGrim/Yamtrack/assets/94771708/6588c057-b64f-43df-9caa-57e197b0875b)
![image](https://github.com/FuzzyGrim/Yamtrack/assets/94771708/0debb122-ce6d-4c14-8c80-62b60c37a6e7)

**Comment by reitenth** [comment]
i had a conflicting port it looks like, it is working with compose i will try getting it in an unraid template

**Comment by FuzzyGrim** [comment]
Yes, in a docker compose file, the part on the right of the ports shouldn't be changed, it's the port that the container uses internally. You can change the part on the left to the port you want to use to access Yamtrack. The same goes for volumes, the part on the right must be `/yamtrack/db` when not using PostgreSQL. So in your case it should look like:

```
version: "3"
services:
  yamtrack:
    container_name: yamtrack
    image: ghcr.io/fuzzygrim/yamtrack
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - SECRET=longstring
      - REDIS_URL=redis://redis:6379
    volumes:
      - /mnt/user/appdata/yamtrack:/yamtrack/db
    ports:
      - "8002:8000"

  redis:
    container_name: yamtrack-redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
```

With this, you should be able to access Yamtrack on port `8002` and have a persistent storage of Yamtrack's data at `/mnt/user/appdata/yamtrack`.
