### ISSUE TITLE
Healthchecks

### ISSUE THREAD

**Issue by vutsalsinghal** [FuzzyGrim/Yamtrack#168]
Hi there,

Love `yamtrack`! 🥳 

Can healthchecks be added to the docker image

```
   healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8000/api/v1/health']
      interval: 30s
      timeout: 2s
      retries: 3
```
