### ISSUE TITLE
[BUG] OIDC required_uris is using plain HTTP

### ISSUE THREAD

**Issue by gnouts** [FuzzyGrim/Yamtrack#365]
**Describe the bug**
I setup OIDC with Authelia as instructed in the wiki.

Login with the provider fails with error 400 :

```
"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. The 'redirect_uri' parameter does not match any of the OAuth 2.0 Client's pre-registered 'redirect_uris'. The 'redirect_uris' registered with OAuth 2.0 Client with id 'xxx' did not match 'redirect_uri' value 'http://yamtrack.domain.com/accounts/oidc/authelia/login/callback/'."
```

**To Reproduce**
yamtrack 0.20.2 accessed by https, latest Authelia with oidc configured.

This is my authelia config
```
      - client_name: "Yamtrack"
        client_id: "xzy"
        client_secret: "$pbkdf2-sha512$xxx"
        consent_mode: implicit
        public: false
        authorization_policy: "one_factor"
        require_pkce: true
        redirect_uris:
          - 'https://yamtrack.domain.com/accounts/oidc/authelia/login/callback/'
#          - 'http://yamtrack.domain.com/accounts/oidc/authelia/login/callback/'
        scopes:
          - "openid"
          - "groups"
          - "email"
          - "profile"
```

If I add the `http://` version, it works. But it shouldn't be necessary

**Expected behavior**
Required_uris should should match the protocol yamtrack is accessed with.

**Yamtrack version**: 0.20.2
**Database**: SQLite
