### ISSUE TITLE
Container doesn´t start (always exits) after updating ti v0.20.4

### ISSUE THREAD

**Issue by Rene1001000** [FuzzyGrim/Yamtrack#369]
My installation on a Synology via Docker worked fine until yesterday evening. The image was updated but the container stopps after a few seconds. Tried a few times bute container always stopps.

**Error logs**
 Operations to perform:

  Apply all migrations: account, app, auth, contenttypes, db, django_celery_beat, django_celery_results, events, lists, mfa, sessions, socialaccount, users

Running migrations:

  No migrations to apply.

id: unknown user abc

deluser: unknown user abc

**Yamtrack version**: 0.20.4
**Database**: SQLite (default)

**Comment by FuzzyGrim** [comment]
I've made some changes in #370, could you try if that fixes it for you?

You would need to change the image tag in your `docker-compose.yml` to image: `ghcr.io/fuzzygrim/yamtrack:pr-370`.

**Comment by Rene1001000** [comment]
Hello,

Thanks,
But I have to say, I´m not very familiar with that.
I installed Yamtrack with this guide: https://mariushosting.com/how-to-install-yamtrack-on-your-synology-nas/

This use a Portainer stack. The stack states:
version: "3.9"
services:
  yamtrack:
    container_name: Yamtrack
    image: ghcr.io/fuzzygrim/yamtrack <http://ghcr.io/fuzzygrim/yamtrack>

Do I have to change only the value behind image:?

BR
Rene

**Comment by FuzzyGrim** [comment]
Yes, that guide uses:

```
services:
  yamtrack:
    container_name: Yamtrack
    image: ghcr.io/fuzzygrim/yamtrack:0.19.9
...
```

You need to change it to:

```
services:
  yamtrack:
    container_name: Yamtrack
    image: ghcr.io/fuzzygrim/yamtrack:pr-370
...
```

And then restart the app, if everything seems to work fine, I will merge the pull request and create a new release with the changes.
