### ISSUE TITLE
[BUG] Setting PUID/PGID makes nginx fail on permission denied

### ISSUE THREAD

**Issue by Cowboy-coder** [FuzzyGrim/Yamtrack#396]
**Describe the bug**

I get this after the webhook plugin in jellyfin calls yamtrack
```
yamtrack                                           | 2025/03/24 20:55:33 [crit] 20#20: *5 open() "/var/lib/nginx/tmp/client_body/0000000001" failed (13: Permission denied), client: 127.0.0.1, server: _, request: "POST /webhook/jellyfin/MY_TOKEN HTTP/1.1", host: "localhost:8000"
yamtrack                                           | 127.0.0.1 - - [24/Mar/2025:20:55:33 +0100] "POST /webhook/jellyfin/MY_TOKEN HTTP/1.1" 500 177 "-" "Jellyfin-Server/10.10.6"

```

**To Reproduce**

I set 
```yaml
  yamtrack:
    image: ghcr.io/fuzzygrim/yamtrack
    container_name: yamtrack
    environment:
      - PUID=1027
      - PGID=65536
      - TZ=Europe/Stockholm
      - SECRET=verysecret
      - REDIS_URL=redis://localhost:6379
    volumes:
      - /volume2/docker/arr-stack/yamtrack:/yamtrack/db
```

and `/volume2/docker/arr-stack/yamtrack` is owned by my user
```
$ ll /volume2/docker/arr-stack/yamtrack
total 748
drwxrwxrwx+ 1 dockerlimited dockergroup     20 Mar 24 21:01 .
drwxrwxrwx+ 1 dockerlimited dockergroup    348 Mar 24 20:53 ..
-rwxrwxrwx+ 1 dockerlimited dockergroup 765952 Mar 24 21:01 db.sqlite3

```

**Expected behavior**

I expect this to work? But im not super familiar with permissions in linux/docker etc so maybe it's a misconfiguration on my part?

**Screenshots**

**Error logs**
 If you have any error logs, paste them here:

**Yamtrack version**:
**Database**: SQLite
