### ISSUE TITLE
Error after updating Docker container

### ISSUE THREAD

**Issue by Rene1001000** [FuzzyGrim/Yamtrack#404]
The error message appeared first after updating to v0.20.5
The error message is yellow, it does not have an influence on correct funtion.

Please see screenshot

**Yamtrack version**: 0.21.0
**Database**: SQLite

![Image](https://github.com/user-attachments/assets/dd0b9a22-24a3-4354-9965-6edbe55754c6)

**Comment by FuzzyGrim** [comment]
From this guide https://mariushosting.com/how-to-install-yamtrack-on-your-synology-nas, they added a custom healthcheck command in the `docker-compose.yml`:

```
services:
  yamtrack:
    container_name: Yamtrack
    image: ghcr.io/fuzzygrim/yamtrack:0.19.9
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
...
 ```

It uses `bash` to check health status, but `bash` is no longer available in the application, you can safely remove that health check section:

 ```
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
 ```

Yamtrack already has a health check built in by default.
