### ISSUE TITLE
Redis password and database

### ISSUE THREAD

**Issue by skibbipl** [FuzzyGrim/Yamtrack#554]
Is it possible to define redis password and database number via environment variables? I have deployed valkey on my network so I want to use it as redis, but I cannot find how to define redis password and database number.
Is this format supported?
```
redis://[[username:]password@]host[:port][/database]
```
Hmm I guess its not compatible 👎🏻
```
Cannot connect to redis://xxxx@valkey.lan:6379/2: invalid username-password pair or user is disabled..
```
OK after some debugging it seems the issue is with my valkey password, it contains comma (,) thus causing urllib.parse to fail:
```
File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
yamtrack  |     raise ValueError(f"Port could not be cast to integer value as {port!r}")
yamtrack  | ValueError: Port could not be cast to integer value as 'xxx'
```
'xxx' is the first part of the password before comma. Could it be possible to fine tune urllib parser to not crash on special characters? I tried to replace `,` with `%2C` but with no luck...

**Comment by FuzzyGrim** [comment]
The error is caused by not escaping the `,` in the `docker-compose.yml`, docker will split the variable in `,` so Yamtrack is receiving `redis://username:pass` instead of `redis://username:pass,word@valkey.lan:6379/2`. You need to escape the variable by wrapping it with quotes, like:

```
- "REDIS_URL=redis://username:pass,word@redis:6379/2"
```

**Comment by skibbipl** [comment]
After quoting the whole variable it does not work:
```
yamtrack  | [2025-06-02 11:18:06 +0200] [25] [ERROR] consumer: Cannot connect to redis://:**@valkey.lan:6379/2: invalid username-password pair or user is disabled..
```
with error from urlib:
```
yamtrack  |   File "/usr/local/lib/python3.12/urllib/parse.py", line 182, in port
yamtrack  |     raise ValueError(f"Port could not be cast to integer value as {port!r}")
yamtrack  | ValueError: Port could not be cast to integer value as 'xxxx'
```

**Comment by FuzzyGrim** [comment]
Okay, I played with the compose file and escaping with `%2C` did work for me:

```
services:
  yamtrack:
    container_name: yamtrack
    image: ghcr.io/fuzzygrim/yamtrack
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - TZ=Europe/Berlin
      - SECRET=longstring
      - REDIS_URL=redis://:mypassword%2Cwithcomma@redis:6379
    volumes:
      - ./db:/yamtrack/db
    ports:
      - "8000:8000"

  redis:
    container_name: yamtrack-redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --requirepass "mypassword,withcomma"

volumes:
  redis_data:
```

```
yamtrack        | [2025-06-02 12:04:24 +0200] [18] [INFO] Connected to redis://:**@redis:6379//
yamtrack        | [2025-06-02 12:04:24 +0200] [18] [INFO] celery@ffc09665700a ready.
```
